### ISSUE TITLE
Produce returns nested drafts when returning a normal table with nested drafts

### ISSUE THREAD

**Issue by Scyfren** [SolarHorizon/immut#11]
This is dangerous for production data as the new state will contain unexpected drafts:
![image](https://user-images.githubusercontent.com/67073142/234966605-7a5eadf2-9ab9-4f3b-a390-e7dcf27990f3.png)

No specific use-case, I was just playing around and tried this out. Usage of roblox-ts will make this issue more likely due to array methods that return new arrays e.g.
```ts
state.nest.find((nest) => nest.value === 0).value += 1
return state.filter((nest) => nest.value !== 0); // will return a normal table containing drafts
```

The fix I thought of was to finalize drafts inside normal table if normal table is returned (see my attempted fix: https://github.com/SolarHorizon/immut/compare/master...Scyfren:immut:fix-non-draft-not-finalized).

However I'm unsure if that's a good fix. Should this just be accepted as intended behavior?

**Comment by SolarHorizon** [comment]
It is a bit weird since we would be altering a value that the user is explicitly returning, but drafts should never exist outside of a producer, so I do think we need to change this behavior.
