### ISSUE TITLE
Produce does not accept nil, string, number and boolean as base

### ISSUE THREAD

**Issue by Scyfren** [SolarHorizon/immut#15]
The following will error:
```lua
produce("", function(draft)
	return "abc"
end)
produce(1, function(draft)
	return 2
end)
produce(true, function(draft)
	return false
end)
produce(nil, function(draft)
	return nil
end)
```
```
ReplicatedStorage.rbxts_include.node_modules.@rbxts.immut.src.Draft:32: Drafts can only be based off of tables. Got string
```

Tried to implement a fix: https://github.com/SolarHorizon/immut/compare/master...Scyfren:immut:fix-produce-to-accept-non-draftable-base

~~But my fix allows tables with metatables. Unsure how exactly @SolarHorizon wants to handle allowing of nil, string, number, boolean as base, so will leave it to him to fix~~
EDIT: Actually, my fix doesn't allow tables with metatables as Draft.new() would throw an error. Will still leave it to SolarHorizon though as I'm unsure if my fix is the approach he would take

**Comment by SolarHorizon** [comment]
Your fix looks good to me! Feel free to PR whenever.
