### ISSUE TITLE
Attempt to call require with invalid arguement(s).

### ISSUE THREAD

**Issue by tracyspells** [SolarHorizon/immut#3]
I've been using RoduxUtils recently (very fun to mess around with) and I ran into an error with the Immut library:
![1](https://user-images.githubusercontent.com/84782396/232132914-dbd7942d-75fa-4ae2-9881-7cb83b355d69.PNG)

In lines 14-15 of the init.lua, you had something like this:
```
local remove = require(script.table.remove)
local insert = require(script.table.remove)
```

For some reason, the `table` folder doesn't exist when I play test my game.
(also both `remove` & `insert` return the same require)

**Comment by SolarHorizon** [comment]
Oh wow. This is a weird one.

Roblox thinks that I am talking about the `remove` method on the instance (which has been deprecated for a very long time) and not the ModuleScript named "remove" inside of it. I will have to reorganize this a bit.

Thanks for reporting this!

**Comment by SolarHorizon** [comment]
Should be fixed in the latest release.
